### ISSUE TITLE
API: need a way to get list of updatable applications

### ISSUE THREAD

**Issue by mardy** [UbuntuOpenStore/openstore-meta#156]
Hi there!
  I was having a look at the Ubports System Settings plugin responsible for dealing with click application updates, in order to port it to the openstore.

I need an API which takes:
 * list of frameworks
 * architecture
 * list of app IDs
and returns a list containing metadata about the requested packages. The current `api/v1/apps` endpoint seems to return exactly what is needed, it only needs to be extented to receive a list of app IDs in order to filter its results.
I've seen that there's also an `api/v1/apps/updates` endpoint, but that seems too limited: it only returns the version number, and no additional medatada about the app (and has no filtering per frameworks or achitecture).

I would suggest adding the list of app IDs to the `api/v1/apps` endpoint, but it could be a good idea to make it available for POST as well, given that the list of app IDs can possible be quite long.

**Comment by bhdouglass** [comment]
We already have support to filter the app list by framework, so that's not really a problem. But you should take a look at what our app does, we are running everything off revision numbers. Our `/api/v2/apps/revision/` is probably what you want for doing updates (supports get and post already).

That being said I don't think it makes a whole lot of sense to handle the app updates as part of the system settings when the OpenStore app already does this.

**Comment by mardy** [comment]
Ah, somehow I missed that endpoint. I'll have a look, thanks.

**Comment by mardy** [comment]
I've found the endpoint now, but it doesn't allow filtering by frameworks or architecture. So how do you know which is the latest revision available, which is still compatible with your device?

**Comment by bhdouglass** [comment]
That's just to tell you which apps can be updated, you can get filter by framework, etc in the apps endpoint.

**Comment by mardy** [comment]
Also, the endpoint does not return all info about the app: name and icon could have changed, and the changelog is not there.

**Comment by bhdouglass** [comment]
Yeah, like i said, it's just for figuring out updates. Everything else about the app can be found in the apps endpoints.

**Comment by mardy** [comment]
Yes I know that the API is complete, but it could be nice if it all could be done in a single query :-)

**Comment by bhdouglass** [comment]
I'm still not sure this is the best option. Leaving the updates in the OpenStore apps is probably better because we can ship updates easily without having to go through an OTA and we can provide any extra flare like alerting the user about permission changes, etc. Plus just look at the example of Google Play.

**Comment by mardy** [comment]
That's a separate issue, I personally like it much better to have it in System Settings, but that's a personal preference. We can make a poll about that, though I'd think that if Canonical designed it that way it's probably a good idea to continue on that track.
Anyway, that's something we can discuss in https://github.com/ubports/ubuntu-touch/issues/184

Here the request is about having the all the information needed to perform an update in a single API call.

**Comment by bhdouglass** [comment]
Determining the best solution based on what Canonical did when their app store wasn't an app like the OpenStore doesn't really make sense. The best solution should here should be based on a factor of both user experience and what technically makes the most sense moving forward.

As for the api for all update info, contributions are welcome and appreciated.
