### ISSUE TITLE
click package not accepted

### ISSUE THREAD

**Issue by derjasper** [UbuntuOpenStore/openstore-meta#177]
I am trying to publish a new release of my app in the OpenStore. I am using clickable for building the package for the first time. My app is a pure QML app. The first problem was, that `--arch all` is not supported by clickable. So I built the click package using `--arch armhf`, but `click-review` says it cannot find any binaries for armhf. Second try was to manually replace all occurrences of `"armhf"` (one in `control.tar.gz/manifest` and one in `control.tar.gz/control`) in the click package by `"all"`. `click-review` accepts the package, but when uploading to OpenStore, it says "There was an error updating your app, please try again later".

Both click packages can be found here:
[click.zip](https://github.com/UbuntuOpenStore/openstore-meta/files/1627207/click.zip)

**Comment by bhdouglass** [comment]
Since you're using clickable you probably want to use one of the `pure*` build templates: http://clickable.bhdouglass.com/en/latest/build-templates.html I'm not sure what your build system looks like so I can't suggest something more helpful.

It sounds like the click package might be malformed since you manually edited it. Try again with clickable and one of the pure build templates and see if that fixes the problem!

**Comment by derjasper** [comment]
Ah thanks! Changing the build template resolved the issue!
