### ISSUE TITLE
[Question][Desgin][Philosophy] Manually installed apps doesn't get listed under «My Apps»

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#192]
Wayne pointed out that if you installed an app that is not in the store, it doesn't get listed so you cannot uninstall it from the OpenStore.

This is not a problem for now as you can tap and hold from Apps Scope and uninstall but it might be if we kill scopes or if we make OpenStore the only replacement for the devices.

Shall we support uninstalling local apps? We support installing them but is it a feature we should have?

**Comment by sverzegnassi** [comment]
My understanding of OpenStore is that we support software that we might reasonably consider "safe", since:
- it might be open source
- it's usable under all the security restriction
- it might come from a "trusted and well-known" UBports or OpenStore contributor 

My opinion is that OpenStore should not provide any tool for installing apps which are not provided by the store, since we can't be 100% it complies with our requirements.
The only exception is when the user installs an app from a different source, and that is also available in our store: in that case, we can be pro-active and suggest the user to install our version instead.

So, for me it's a no - but multiple answers are really possible for this topic  

The ideal solution is that Ubuntu Touch provides all the means to install/manage/remove applications that come from different sources than OpenStore.

**Comment by bhdouglass** [comment]
I'm going to close this out, but I second @sverzegnassi's opinion, Ubuntu Touch should handle installing & removing apps from outside of the OpenStore.
