### ISSUE TITLE
OpenStore app main page 'New and updated' section shows only new apps

### ISSUE THREAD

**Issue by TronFortyTwo** [UbuntuOpenStore/openstore-meta#208]
This issue is explained by the two screenshot that I attached. You can see that there are missing apps in the main page (the updates).
![screenshot20180819_193357261](https://user-images.githubusercontent.com/18293963/44311436-c43e7300-a3e7-11e8-98f2-885dd89bb3ad.png)
![screenshot20180819_193351482](https://user-images.githubusercontent.com/18293963/44311437-c43e7300-a3e7-11e8-9ce4-0a84aa0fc68d.png)

**Comment by bhdouglass** [comment]
Which page are you calling the "main page"?

**Comment by TronFortyTwo** [comment]
With the 'main page' I mean the first page you see when you open the OpenStore, the one with the carousels and the banner with the featured app.

**Comment by bhdouglass** [comment]
Gotcha, just making sure we are on the same page (pun intended). So the main page's "New and Updated Apps" section is the newest 10 apps and 10 latest updates combined and we only present the latest 10 of those. Since the new apps are also marked as updates it could be that the actual updates are being hidden. And there is also some caching involved.
